version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "80:80"
    networks:
      - webnet
    depends_on:
      - app

  app:
    build: ./app
    ports:
      - "8000:8000"
    networks:
      - webnet
      - appnet
    depends_on:
      - db

  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - appnet

networks:
  webnet:
  appnet:
